### ISSUE TITLE
[22] Umbrella bug for IDE support for relevant Java 22 features

### ISSUE THREAD

**Issue by mpalat** [eclipse-jdt/eclipse.jdt.core#2162]
Refer #1397 

IDE Support for the relevant Java 22 features:

- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2083
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2086
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2084
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2085
- [ ] https://github.com/eclipse-jdt/eclipse.jdt.core/issues/2151
